version: '3.8'

services: 
  server:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - database
  
  database:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_USER=AshUser
      - POSTGRES_PASSWORD=AshLeaf
      - POSTGRES_DB=AshData
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "1234:5432"
        
volumes: 
  pgdata: